<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{82f0ea0d-1406-4204-9446-c1968db403d4}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	
bool1				:	BOOL;

deskbool			:	BOOL;

lapbool				:	BOOL;

mainBranchLapBool2	:	BOOL;

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>